url: "wanghaoyu.xyz"
# baseurl: Hanchao-Zhang.github.io
# Basic Information
title: Haoyu Wang
# subtitle:
position: M.A. Student in Communication Science
affiliation: Renmin University of China
subaffiliation: School of Journalism and Communication
affiliation_link: https://en.ruc.edu.cn/
subaffiliation_link: http://jcr.ruc.edu.cn/English/index.htm
email: wanghaoyu@ruc.edu.cn
address: 59 Zhongguancun Ave, Haidian, Beijing, 100089 
address_link: https://www.google.com.hk/maps/search/%E4%B8%AD%E5%9B%BD%E4%BA%BA%E6%B0%91%E5%A4%A7%E5%AD%A6/@35.4866992,113.5988749,6z/data=!3m1!4b1?hl=zh-CN&entry=ttu

# Search Engine Optimization (SEO)
keywords: minimal light
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light-theme.yliu.me/

# Links
cv_link: ./assets/Wang Haoyu_CV.pdf
twitter: https://x.com/wangharri

# Images
avatar: ./assets/haoyu.jpg
favicon: ./assets/avatar2.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: false

# Google Analytics ID
google_analytics: G-TLBTYV5YVR

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
